baseURL = "https://breguetman.com"
languageCode = "en-us"
title = "BreguetMan"
theme="archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle="Test"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/breguetman"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

#[[menu.main]]
#name = "All posts"
#url = "/posts"
#weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
